name: Run Custom Checkov Policies
description: Runs Custom Checkov Policies on SAM/CloudFormation templates

inputs:
  framework:
    description: The framework of the templates to scan
    required: false
    default: cloudformation
  ref:
    description: The ref (tag/branch) of security-checks to load checks from
    required: false
    default: v1

runs:
  using: composite
  steps:
    - name: Checkout security-checks repo (to get custom checks)
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: govuk-one-login/security-checks
        ref: ${{ inputs.ref }}
        path: .security-checks
        fetch-depth: '1'

    - name: Get changed files
      id: diff
      shell: bash
      run: |
        FILES=$(git diff --name-only origin/main...HEAD -- '*.yaml' | tr '\n' ' ')
        echo "files=$FILES" >> "$GITHUB_OUTPUT"

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.12' # This is the latest version of Python supported by Checkov

    - name: Install Checkov
      shell: bash
      run: pip install checkov

    - name: Run Checkov
      shell: bash
      run: |
        checkov -f ${{ steps.diff.outputs.files }} \
          --framework ${{ inputs.framework }} \
          --external-checks-dir .security-checks/src/checks/ \
          --output cli \
          --output sarif \
          --output-file-path console,results.sarif

    - name: Upload SARIF results
      if: always()
      uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
      with:
        sarif_file: results.sarif
        category: security-checks
